spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testdb?useUnicode=true&characterEncodeing=utf8&serverTimezone=Asia/Seoul
    username: ryewon
    password: fpdnjs123!@#
    
logging:  level: 
    com.ryewoncode.mybatisRestApi2:
      CompanyMapper: TRACE
      EmployeeMapper: TRACE